### ISSUE TITLE
ununtu20.4  AttributeError: type object 'DesiredCapabilities' has no attribute 'PHANTOMJS'

### ISSUE THREAD

**Issue by YiJiuChow** [kanomahoro/nonebot-twitter#1]
![S$EFY @5R NDP6SQDK(G`QN](https://user-images.githubusercontent.com/64878354/144585526-21fd2dad-f9b7-459a-be62-cef16c20f29f.png)
搜了一圈没搜到怎末解决

**Comment by kanomahoro** [comment]
不要在宿主环境安装，请参考视频教程和文档配置。

**Comment by YiJiuChow** [comment]
> 频教程和文档配置。

好的
但是我之前在windows宿舍主环境安装,就可以,换ubuntu就不行了
