### ISSUE TITLE
代理服务器设置相关

### ISSUE THREAD

**Issue by KafCoppelia** [kanomahoro/nonebot-twitter#3]
twitter连接报错，大致这两条错误，`ConnectionRefusedError: [Errno 111] Connection refused`、`urllib.error.URLError: <urlopen error [Errno 111] Connection refused>`，expor的代理服务器所在地为国外，端口号8080，在Aliyun ECS内也设置了相应的安全组。是需要proxychain + shadowsocks使用么？

**Comment by kanomahoro** [comment]
phantomjs新版本已废弃，请及时更新
