### ISSUE TITLE
在云服务器上挂了一会就提示apscheduler报错，keyerror timeline，该怎么解决？

### ISSUE THREAD

**Issue by krasus1995** [kanomahoro/nonebot-twitter#7]
![736O2Y4}ZFDWA5DSEOQR3TL](https://user-images.githubusercontent.com/97447697/152203462-c68c0aef-1eba-4488-a401-7a1c18dac452.png)

**Comment by ppquake** [comment]
你解决了吗，我的也是这个地方报错 KeyError: 'entries'

**Comment by kanomahoro** [comment]
推特修改了API接口，已修复，请直接使用源码安装。
